#!/bin/sh
OUTPUT_FILE="./spiffs_filesystem_partition.bin"
# flash size for the ESP8266-12E
FLASH_SIZE="4MB"

# Refer to ./build/flash_project_args for the autogenerated version
python $IDF_PATH/components/esptool_py/esptool/esptool.py\
 --chip esp8266\
 -p $ESPPORT -b 460800\
 write_flash --flash_mode qio --flash_freq 40m --flash_size $FLASH_SIZE\
 0x110000 "$OUTPUT_FILE"
